export const FETCH_CAPITAL_BEGIN   = 'FETCH_CAPITAL_BEGIN';
export const FETCH_CAPITAL_SUCCESS = 'FETCH_CAPITAL_SUCCESS';
export const FETCH_CAPITAL_FAILURE = 'FETCH_CAPITAL_FAILURE';
export const ADD_CAPITAL = 'ADD_CAPITAL';
export const REMOVE_CAPITAL = 'REMOVE_CAPITAL';
export const TOGGLE_WANT_TO_VISIT = 'TOGGLE_WANT_TO_VISIT';
export const TOGGLE_VISITED = 'TOGGLE_VISITED';
export const SORTBY = 'SORTBY';